### ISSUE TITLE
Cashbook transactions with tax rate None and a tax value are not saved

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#217]
When a cashbook payment is saved and a tax value is entered but the tax rate is left as 'None' uzERP will display a success message but the transaction is not saved.

This should be caught on save and an error displayed to the user.

**Comment by steveblamey** [comment]
Need to check with @mshiner what combinations of net value, tax value and 'None' tax rate are valid for accounting purposes.

**Comment by mshiner** [comment]
Basically if tax rate is None then tax MUST be zero. None means the transaction is 'outside of scope' and does not appear on the VAT return so it MUST be zero or the GL will be wrong. I assume this is why the transaction is failing silently because the GL is complaining rather than the cashbook code.

If tax rate is set to something other than none it is up to the user to enter the correct tax for the rate - the system doesn't calculate the value (and nor should it) as it may or may not be equal to the calculated value (especially in the case of purchases) because of rounding issues.

**Comment by steveblamey** [comment]
`CBTransaction::saveCashPayment()` does not check for errors after calling `CBTransaction::saveGLtransaction()`. After adding a check for errors after saving the GL Transaction I made test payments with the following results:

Test Ref | E | F | G | H | I | J
--: | --: | --: | --: | --: | --: | :--
**Net Value** | 0 | 1 | 1 | 0 | 1 | 1
**Tax Value** | 1 | 0 | 1 | 1 | 0 | 1
**Rate** | None | None | None | Std | Std | Std
**Saved?/Error** | Transaction total must equal zero. It equals: -1.00 | Yes | Transaction total must equal zero. It equals: -1.00 | Yes | Yes | Yes

@mshiner is the above the correct behaviour in each case?

**Comment by steveblamey** [comment]
Confirmed that the above failed/success states are correct.

**Comment by mshiner** [comment]
@steveblamey - as discussed the logic above is correct.
